export enum ActionTypes {
  FETCH_TRANSCRIPT = 'FETCH_TRANSCRIPT',
  FETCH_TRANSCRIPT_PENDING = 'FETCH_TRANSCRIPT_PENDING',
  FETCH_TRANSCRIPT_FULFILLED = 'FETCH_TRANSCRIPT_FULFILLED',
  FETCH_TRANSCRIPT_REJECTED = 'FETCH_TRANSCRIPT_REJECTED',
  FETCH_SEQUENCE = 'FETCH_SEQUENCE',
  FETCH_SEQUENCE_PENDING = 'FETCH_SEQUENCE_PENDING',
  FETCH_SEQUENCE_FULFILLED = 'FETCH_SEQUENCE_FULFILLED',
  FETCH_SEQUENCE_REJECTED = 'FETCH_SEQUENCE_REJECTED'
}